### ISSUE TITLE
As an admin or restaurant I want to be able to effectively order my list of products in a menu category

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#2983] opened 2021-12-23 00:16 UTC
**Describe the bug**
I reorder products in a menu category, but after saving they revert to original position.

**To Reproduce**
1. Have restaurant
2. have menu with products
3. not sure if anything else required
4. move items
5. save
6. see them in original position

**Expected behavior**
The products stay where i have moved them

**Screenshots**

https://user-images.githubusercontent.com/77277854/147169158-2cd916e2-1826-4295-82dc-6aadae50e966.MOV

**Desktop (please complete the following information):**
 - Browser firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ERAMANrepartos** [comment] 2023-05-04 12:54
duplicate of #1464

**Closed** 2024-10-16 21:41 UTC
Labels: bug, Restaurant Interface, Food Tech
