### ISSUE TITLE
options layout

### ISSUE THREAD

**Issue by damienlapoitavelo** [coopcycle/coopcycle-web#872] opened 2019-11-14 09:11 UTC
We have a problem with a new restaurant. It need some options because customers choose all the content of their bowls and it's impossible to put the drink at the end.
Another problem is to choose more of one values but less of 2 or 4 values. We can choose only one or all values without limit.
![Capture](https://user-images.githubusercontent.com/43618873/68842698-1e9bb180-06c7-11ea-9928-aa114819d52f.PNG)

**Comment by alexsegura** [comment] 2019-11-28 07:58
Closing as duplicate of #380 for sorting options

**Closed by alexsegura** 2019-11-28 07:58 UTC
