### ISSUE TITLE
Ability to add stock levels for food items.

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1401] opened 2020-05-06 10:33 UTC
The restaurant can indicate they have 10 items of a certain product, so when customers have ordered what the stock level/inventory allows, the product is disabled automatically.

**Comment by joel-shiftdelivery** [comment] 2020-05-06 16:50
While I agree this would be beneficial for some situations, it would also mean that people ordering in advance wouldn't be able to order their desired item, even if it will be back in stock by their selected delivery time.

**Comment by agichim** [comment] 2020-05-26 20:42
Implementing inventory would be very helpful also for Click&Collect. The restaurant we're working with is usually very busy so they will have a hard time to keep track of the orders and disable the products that run out.

**Comment by alexsegura** [comment] 2020-07-23 15:53
Duplicate of #1580
Let's continue discussion there. 

This has been asked by at least 3 co-ops, so even if I see potential problems with this, this needs to be discussed because it seems to be a real world problem. 
Also see #1355

**Closed by alexsegura** 2020-07-23 15:53 UTC
