### ISSUE TITLE
Import is too slow and may timeout if > 50 tasks

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#222] opened 2018-02-21 11:38 UTC
Reported by Raphael

**Comment by alexsegura** [comment] 2018-02-21 11:41
This is due to geocoding. 
First, we can increase the max execution time as a quick workaround. 
Then, it would be cool to have some queue system to perform long running tasks.

**Comment by alexsegura** [comment] 2018-03-14 09:17
I couldn't reproduce it locally, can you?

**Comment by alexsegura** [comment] 2019-10-06 11:05
Would be fixed by #721

**Closed** 2020-03-03 09:23 UTC
Labels: bug, enhancement
