### ISSUE TITLE
In order to avoid new orders left without restaurant approval

### ISSUE THREAD

**Issue by ChloeOLVO** [coopcycle/coopcycle-web#2173] opened 2021-03-08 13:38 UTC
Current issue:
1/ Sometimes restaurants do not approve (forget to approve or do not see the new order notification) an order and the client remains without information about what is going on with its order
2/ Sometimes restaurants approve a new order way too late and we face difficulties, as a delivery company, to respect delivery slot for the client (we have the information too late)

Proposal:
a) If a restaurant do not approve a new click and collect order X min (to be defined by restaurant) before the delivery slot (or 10 min after the "délais addtionnel pour les prises de commandes" if the restaurant), it should be concidered as cancelled
b) a) If a restaurant do not approve a new delivery order X min (to be defined by delivery company "admin") before the delivery slot (or 15 min after the "délais addtionnel pour les prises de commandes" if the restaurant) , it should be concidered as cancelled

Impact for clients:
If a new order is cancelled because the restaurant do not approve it, within criterias described above, the client receives an email notification saying "your order has been cancelled because the restaurant did not approve within the good time laps. For futher information, please get in contact with the restaurant directly."

**Comment by alexsegura** [comment] 2022-02-11 15:10
Duplicate of #425

**Closed by alexsegura** 2022-02-11 15:10 UTC
Labels: enhancement
