### ISSUE TITLE
[RESTAURANTS] Allow creating pretty URLs

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#2548] opened 2021-06-20 08:51 UTC
`https://york.coopcycle.org/en/store/11-atelier-creativa` - **Original URL**
`https://york.coopcycle.org/atelier-creativa` - **Pretty URL**

**Comment by alexsegura** [comment] 2021-06-23 16:08
Duplicate of #1933

**Closed by alexsegura** 2021-06-23 16:08 UTC
Labels: enhancement
