### ISSUE TITLE
Not possible to download proof of delivery

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3610] opened 2023-05-03 09:57 UTC
![bug](https://user-images.githubusercontent.com/44605344/235886144-d1a4b459-432a-4904-b75d-f07f78a75779.gif)

**Comment by ERAMANrepartos** [comment] 2023-05-04 08:02
Hey, so it looks like photos are accesable in two places:
1. here, where a pdf is printed using a 3rd party service, which here has had an error due to the total size of the photos
2. A shop dashboard where there is a history of the services of the shop, where there is a camera icon that will download a zip file with all the photos - this should still be working.

So while it looks like we can solve this issue today (to be confirmed) the best practices here is to have these tasks associated with a shop, which also avoids this issue

**Comment by alexsegura** [comment] 2023-05-04 10:25
Struggling the restart browserless with new env var in production because of docker/docker-py#3113

**Comment by alexsegura** [comment] 2023-05-05 10:59
Fixed by increasing `MAX_PAYLOAD_SIZE` to 20mb

**Closed by alexsegura** 2023-05-05 10:59 UTC
Labels: bug
