### ISSUE TITLE
Multi dropoff tasks created by store are not correctly displayed 

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#3265] opened 2022-06-09 12:57 UTC
**Describe the bug**
The muti dropoff tasks created in a store are displayed in a wrong order (in the not assigned tasks window) 
In addition, the second (and the followings) dropoff doesn't have the color flag (on the left side).

**To Reproduce**
1. Create a multi dropoff task (1PU and min 2 dropoff)
2. See on dashboard
<img width="276" alt="image" src="https://user-images.githubusercontent.com/44605344/172851871-2a9b6080-cbfc-4ab2-a7f3-def422cb916b.png">

**Comment by ERAMANrepartos** [comment] 2023-04-27 21:48
I put a quickfix tag but im not sure thats true. I believe the issue may be due to the tasks not being correctly associated with each other at a more basic level. I believe this may be able to be fixed with the new features we are created related to the universal export and routes (which requires certain things, such as a new conceptualization of how tasks are associated with each other)
@lucasferraro

**Comment by Paul-Eraman-CoopCycle** [comment] 2023-10-09 14:30
🥳

**Comment by Paul-Eraman-CoopCycle** [comment] 2023-10-10 15:56
![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/e472968f-e41b-4acb-be4a-86ae80f1314a)

I think its still broken

**Comment by r0xsh** [comment] 2023-10-20 07:13
What is the expected behavior @Paul-Eraman-CoopCycle ?
Should tasks be ordered by id ?

**Comment by Paul-Eraman-CoopCycle** [comment] 2023-10-20 07:15
Well at a minimum, all the dropofs should have the same color line for sure

the order is less important i think, but in task ID order makes sense I guess

**Comment by rayon9coop** [comment] 2023-10-20 07:30
Yes, indeed, both colors and order are important for us. But both seems fixed
![image](https://github.com/coopcycle/coopcycle-web/assets/44605344/41b0ad4f-cfb0-4f80-96a4-798572507721)
![image](https://github.com/coopcycle/coopcycle-web/assets/44605344/84899659-3292-44ee-8ac1-fdd6384c0cbe)

**Comment by Paul-Eraman-CoopCycle** [comment] 2023-10-20 07:39
Ok cool! Closing then 🥳

**Closed by Paul-Eraman-CoopCycle** 2023-10-20 07:39 UTC
Labels: bug, UI/UX, last mile, quickfix
