### ISSUE TITLE
Whenever I have an order with the Punjab restaurant, it displays "test" in bold instead of the restaurant name.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-web#2673] opened 2021-05-09 09:16 UTC
Whenever I have an order with the Punjab restaurant, it displays "test" in bold instead of the restaurant name.

![bug nom resto](https://user-images.githubusercontent.com/83431363/117566627-00462480-b0b8-11eb-8638-beb7db2e67ba.png)

**Comment by alexsegura** [comment] 2021-08-04 07:13
Duplicate of #2528

**Closed by alexsegura** 2021-08-04 07:13 UTC
