### ISSUE TITLE
Order: Item option is applied only on one item

### ISSUE THREAD

**Issue by taratatach** [coopcycle/coopcycle-web#1430] opened 2020-05-18 17:45 UTC
When ordering from a restaurant, if you select an item which has options, the selected option is applied only on one item if you order more than one.

You can see an example of such an order below:
![Capture d’écran de 2020-05-18 19-40-46](https://user-images.githubusercontent.com/580382/82243421-db552080-993f-11ea-9791-90e056319ccb.png)

Only one Shahi will be ordered with Tofu.

**Comment by alexsegura** [comment] 2020-05-20 08:38
I can't reproduce the problem, see GIF below

![escale_indienne](https://user-images.githubusercontent.com/1162230/82424793-f8940700-9a85-11ea-8dc7-b9fd428c58a3.gif)

**Comment by taratatach** [comment] 2020-05-23 12:09
Hi @alexsegura.

Thanks for the video :). If you check the cart, you'll see that the options under item show "1x Dés de tofu".
It happens I had to call the restaurant about my order and they thought there was only 1 Tofu order as well.

Maybe it's just a misunderstanding but if the restaurant does not understand the option applies to all the items it's going to be a problem :).

**Comment by alexsegura** [comment] 2020-05-24 04:02
Ok, then it's more a UI/UX problem. 

Actually, when it's written: 
```
2 x Shahi Poireau
  - 1 x Dés de tofu bio
```

It means there are 2 "menus", and each of them have 1 x the option. 
I don't have any idea to do this better, as in our system, some options may be added several times.
Like for example, if you have "12 samoussas, choose your preferred tastes". 

We don't have millions of orders, but we have some, and I don't have people reporting this to me all day (about restaurant making mistakes). I think this was a mistake from the restaurant, they are on the platform for a few months.

**Comment by taratatach** [comment] 2020-06-10 08:17
I would suggest dropping the number when the option applies to every item of a menu (i.e. options are selected

e.g.:
```
2 x Shahi Poireau
  - Dés de tofu bio
```

When the options can be enumerated, the number of each is displayed:

e.g.:
```
12 x Samoussas
  - 9 x Légumes
  - 3 x Bœuf
``

**Comment by ERAMANrepartos** [comment] 2023-04-25 22:14
Specific use case, closing issue but adding UI/UX tag in case someone wants to look back at it. In general, how orders are represented needs to be rethought from the ground up

**Closed by ERAMANrepartos** 2023-04-25 22:14 UTC
