### ISSUE TITLE
Possibility delete assigned courriers

### ISSUE THREAD

**Issue by TifaineSicklo** [coopcycle/coopcycle-web#1103] opened 2020-01-25 13:25 UTC
Filters just delete the geolocalisation on the map but not the courriers on the administration panel. For intern organisation, for dispatch it can be easier to see its own courriers assigned each time during one day (planning can change every time).

**Comment by alexsegura** [comment] 2021-03-16 09:47
Duplicate of #1354

**Closed by alexsegura** 2021-03-16 09:47 UTC
