### ISSUE TITLE
500 Error on invoices from admin/orders/{id}.pdf ( admin_order_invoice )

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#289] opened 2018-04-04 17:57 UTC
@alexsegura can you look at it ? I don't get this symfony black magic.

**Comment by alexsegura** [comment] 2018-04-05 15:11
Fixed in 08199ab2fd1f62e8856b2690d0b19efb70ca4217

**Closed by alexsegura** 2018-04-05 15:11 UTC

**Comment by alexsegura** [comment] 2018-04-05 15:15
Just to explain: it is caused by the precedence of route patterns. 
Actually Symfony router iterates over the patterns defined to try to find a route. 

To match the routes, the route with `.pdf` at the end needs to be first obviously:
- `/profile/orders/{id}.pdf`
- `/profile/orders/{id}`


But, as we were defining some of the routes in YAML files, and some other via annotations, the order was unpredictable. 
So I defined everything in YAML files, and moreover I changer the route for the invoice 🙂
