### ISSUE TITLE
for the customer of the business group : miss in the topar a big button "ORDER WITH MY COMPANY" (account switch)

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#4317] opened 2024-05-23 16:34 UTC

**Comment by lucasferraro** [comment] 2024-05-27 19:15
@Atala 
Is this duplicate of https://github.com/coopcycle/coopcycle-web/issues/4315?

**Comment by Atala** [comment] 2024-05-28 07:23
mmm not exactly, i think we need both :
- something that show the user he is ordering with his company (current state = business mode)
- a switch action that show the user he can go in/out business mode (not buried in the dropdown but clearly stated)

but i think a good design could do both in one go. we can ask vincent for this if needed

(also as i say in another issue be aware of the screen size tablet when putting things in the topbar)

**Closed** 2024-06-13 08:15 UTC
Labels: bug, Platform Catering
