### ISSUE TITLE
docker-compose fail: unable to fetch acpu from pecl - connection issue?

### ISSUE THREAD

**Issue by kiwi4boy** [coopcycle/coopcycle-web#238] opened 2018-02-26 18:22 UTC
Hello all,

I've been trying to start my Docker image with `docker-compose up`, but I got the following error when Docker is trying to pack PHP:

```
+pecl install apcu-5.1.8
No releases available for package "pecl.php.net/acpu"
install failed
ERROR: Service ‘php’ failed to build: The command '...’ returned a non-zero code: 1
```

From support sites such as [this](https://github.com/docker-library/php/issues/536), it seems that it is complaining that I'm in a proxy.  However, I'm not under a proxy environment.

Could anyone please help me dig further what is the issue, please?  Thanks,

**Comment by ccoreilly** [comment] 2018-02-27 09:59
The address pecl.php.net/**acpu** doesn't exist, it should be pecl.php.net/**apcu**. However I can only reproduce the error if I run the command with the typo:
`pecl install acpu-5.1.8`

Did you change anything in docker/php/Dockerfile?

**Comment by kiwi4boy** [comment] 2018-02-27 18:21
Hello ccoreilly,

No, I did not change anything in docker/php/Dockerfile, and indeed, it's spelt pecl.php.net/**apcu** in the Dockerfile:

```
killall Xvfb' > /usr/bin/wkhtmltopdf \
    && chmod +x /usr/bin/wkhtmltopdf \
    && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
    && docker-php-ext-configure pdo_pgsql --with-pgsql \
    && docker-php-ext-install \
        intl \
        pdo_pgsql \
        zip \
        bcmath \
    && pecl install \
        apcu-${APCU_VERSION} \
    && docker-php-ext-enable --ini-name 20-apcu.ini apcu \
    && docker-php-ext-enable --ini-name 05-opcache.ini opcache \
    && apk del .build-deps
```

**Comment by ccoreilly** [comment] 2018-02-27 20:32
If you keep getting the same error when building the php container (`docker-compose build --no-cache php`) then maybe you could try deleting these lines in the docker/php/Dockerfile:
```
    && pecl install \
        apcu-${APCU_VERSION} \
```
And rebuilding the container. If it builds correctly you can try running the command `pecl install apcu-5.1.8` in the container:
`docker-compose run -u root php pecl install apcu-5.1.8`

If you keep seeing the error I do not know what the reason could be. I had an issue with my local dns server not resolving the dl-cdn.alpinelinux.org domain and had to change my DNS to 8.8.8.8

**Comment by alexsegura** [comment] 2018-03-20 22:57
Do you still experience the issue? I just built my php container again without trouble. 

I see this in the logs: 
```
+ pecl install apcu-5.1.8
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
```

**Comment by alexsegura** [comment] 2019-02-16 11:13
The Docker container has changed a lot since this issue was opened, closing.

**Closed by alexsegura** 2019-02-16 11:13 UTC
