### ISSUE TITLE
In order to spend less time coordinating stops As a dispatcher I want the add the right click option "move to next workday"

### ISSUE THREAD

**Issue by GuidoHaagen** [coopcycle/coopcycle-web#2068] opened 2021-01-27 15:18 UTC
**In order to**  spend less time clicking stops to the next day. 
We often have to push 10 to 30 stops per day to the next workday to deliver them. 

**As a** dispatcher
I now have to click a lot of times to move one stop to the next day. 

**I want** the option to select multiple stops and right click them and choose something like: move to next (work) day. 

**Whereas currently** today you have to click around 7 times for one stop.

**Comment by alexsegura** [comment] 2021-02-10 11:47
Duplicate of #1356

**Closed by alexsegura** 2021-02-10 11:47 UTC
Labels: enhancement
