### ISSUE TITLE
Possibility of hiding/showing tasks in unassigned tours

### ISSUE THREAD

**Issue by 0bi0ne1312** [coopcycle/coopcycle-web#4570] opened 2024-08-14 10:05 UTC
In order to simplify the assignment of tasks and the creation of routes

I would like to propose to have a feature of hiding/showing unassigned tours to clear the map and show only assigned tasks and unassigned tasks.
I made a drawing :)

The idea is to clear the map of already sorted tasks to make it more clearer to assign the rests and see only the ongoing tasks (the one that are assigned and about to be made / the one that just dropped or are left to be assigned)
![Uploading HIDE.PNG…]()
![image](https://github.com/user-attachments/assets/64dcc35d-3be5-4f13-a2b6-a6b7b0be3014)

**Comment by Atala** [comment] 2024-08-22 09:57
@0bi0ne1312 is it duplicate of #4207 ? it seems so to me . i will move your message to this issue

please reopen if not,

**Closed by Atala** 2024-08-22 09:57 UTC
Labels: enhancement
