### ISSUE TITLE
Improve access to package description (string, type, weight, volume…) in the dispatch panel

### ISSUE THREAD

**Issue by vdegove** [coopcycle/coopcycle-web#601] opened 2019-07-11 14:57 UTC

**Comment by couleurmate** [comment] 2020-04-08 15:37
COVID19 ? 

Introduction to manage unit of delivery and add sanitary conditions

**Comment by alexsegura** [comment] 2022-02-02 14:32
Duplicate of #3043

**Closed by alexsegura** 2022-02-02 14:32 UTC
Labels: last mile
