### ISSUE TITLE
PayPal!

### ISSUE THREAD

**Issue by 552020** [coopcycle/coopcycle-web#1348] opened 2020-04-24 17:28 UTC
Now!

**Comment by alexsegura** [comment] 2020-04-24 17:35
Duplicate of #704 🙂

**Closed by alexsegura** 2020-04-24 17:35 UTC

**Comment by 552020** [comment] 2020-04-24 18:18
:_(Am 24.04.2020 19:35 schrieb Alexandre Segura <notifications@github.com>:
Closed #1348.
