### ISSUE TITLE
International phone numbers are not displayed correctly

### ISSUE THREAD

**Issue by VShell** [coopcycle/coopcycle-web#2140] opened 2021-02-22 19:16 UTC
**Describe the bug**

I'm in Germany, and only have a UK phone number so far. I created an account on khora.berlin, where my phone number was displayed without the "0044" prefix.

**To Reproduce**

1. Go to 'khora.berlin' and register with a UK phone number
2. Go to your profile
3. See the phone number displayed without the 0044 prefix

**Expected behavior**

The 0044 prefix is visible in the phone number. I also expect that this is visible from the courier's view.

**Desktop (please complete the following information):**
 - OS: NixOS Linux
 - Browser: Firefox

**Comment by alexsegura** [comment] 2021-02-24 12:40
Hi, 

Thanks for reporting this. 

The problem is that currently, the system lets you enter your phone number in the "national" format (i.e, without any prefix), and this is parsed and stored in the E.164 format in database. But when you enter the phone number in the "national" format, the system supposes it's a German number. 

You can still enter your phone number directly in the E.164 format (like `+4401234567`), and this will work, but there's nothing in the UI indicating this. 

To fix this properly, i.e to allow entering any phone number from any country, we would need to use a widget that allows selecting the country code, like [intl-tel-input](https://github.com/jackocnr/intl-tel-input) or [react-phone-number-input](https://catamphetamine.github.io/react-phone-number-input/)

**Comment by alexsegura** [comment] 2021-02-24 12:41
Related to #2053

**Comment by VShell** [comment] 2021-02-25 12:46
Going into my account and editing my phone number to +44<my number>, it still displays without that prefix in my profile (just 0<my number>, as I'd expect a UK national number to be displayed to be called from the UK), and gets stored as 0044<my number> as evidenced by the edit form displaying it as that.

**Comment by Paul-Eraman-CoopCycle** [comment] 2023-09-02 00:01
Repeat issue, closing '

**Closed** 2023-09-02 00:01 UTC
Labels: bug, quickfix
