### ISSUE TITLE
Choosing a delivery time slot even if the restaurant is closed

### ISSUE THREAD

**Issue by rayon9coop** [coopcycle/coopcycle-web#1938] opened 2020-11-25 06:19 UTC
**Describe the bug**
For restaurants, while closing day are encoded in the planning, the closed day appaers in the scrolling list when ordering.

**To Reproduce**
Encode closing days
Define time slot for delivery
Try to order and see the closed day in the scroll menu

**Expected behavior**
Not showing the days of closing in th scrolling menu to avoid false joy to the customer

**Screenshots**
<img width="455" alt="2020-11-25 07_05_06-RAYON9" src="https://user-images.githubusercontent.com/44605344/100190425-8269d480-2eee-11eb-9228-5a989687a124.png">
<img width="651" alt="2020-11-25 07_11_23-Glacier Frysa - RAYON9" src="https://user-images.githubusercontent.com/44605344/100190453-8e559680-2eee-11eb-86d0-d613069732f5.png">

**Comment by alexsegura** [comment] 2020-12-26 17:43
Duplicate of #1969

**Closed by alexsegura** 2020-12-26 17:43 UTC
Labels: bug
