### ISSUE TITLE
The order of the options, of the products in the menu is not respected. A customer who wants to buy a kebab can see a suede pie first, then the sauces, then the drinks, and finally his kebab.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-web#2679] opened 2021-04-30 10:27 UTC
The order of the options, of the products in the menu is not respected. A customer who wants to buy a kebab can see a suede pie first, then the sauces, then the drinks, and finally his kebab.

**Comment by alexsegura** [comment] 2021-08-04 07:33
Duplicate of #2576

**Closed by alexsegura** 2021-08-04 07:33 UTC
