### ISSUE TITLE
Allow creating orders from the back-office for restaurants

### ISSUE THREAD

**Issue by Yao199** [coopcycle/coopcycle-web#1451] opened 2020-06-01 09:49 UTC
In order to adapt to all restaurants situation, it would be useful to add the possibility to create orders from the back office. 

It is useful so the restaurants can pass an order if the client calls directly the restaurant

**Comment by alexsegura** [comment] 2020-06-26 14:39
Duplicate of #272

**Closed** 2020-06-26 17:03 UTC
Labels: enhancement
