### ISSUE TITLE
Return a more significant error when an address can't be geocoded

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#864] opened 2019-11-13 09:23 UTC
When an address can't be geocoded, any request that uses the geocoder (for example `/api/deliveries/*` with `dropoff.address` as a string) returns the following error: 

```
Fatal error: Call to a member function getGeo() on null
```

It is because the following code doesn't care if the address is empty:

https://github.com/coopcycle/coopcycle-web/blob/6b80d88f66e5c7e0f547e36e225439d6bb632986/src/AppBundle/Serializer/DeliveryNormalizer.php#L91-L100

**Comment by vladimir-8** [comment] 2024-10-09 22:51
Duplicate of https://github.com/coopcycle/coopcycle-web/issues/1574

**Closed by vladimir-8** 2024-10-09 22:51 UTC
Labels: enhancement
