### ISSUE TITLE
fix: the delivery form gets broken if the total price of the order is 0

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#4200] opened 2024-04-23 19:46 UTC
**In order to**  `prevent setups that can put delivery form in a broken state`

**I want** `to be decided`

Allow to make free deliveries

Prevent a customer from continuing if a total price turns out to be 0

Warn cooperatives about such situations while setting up the tariffs (could be hard to check all possible cases with all possible tariffs)

Anything else?

**Whereas currently** `the form gets broken if the total price of the order is 0`

**Additional context**

https://coopcycle.slack.com/archives/C4UT4DGQ3/p1713894191070909

**Comment by Paul-Eraman-CoopCycle** [comment] 2024-10-13 19:00
duplicate of https://github.com/coopcycle/coopcycle-web/issues/4557
will track there

**Closed** 2024-10-16 23:36 UTC
Labels: enhancement
