### ISSUE TITLE
 To be able to offer reductions (gift card). Example, a customer wants to offer 10 € to a friend, he pays and receives a code for the amount.

### ISSUE THREAD

**Issue by Carlitofastandcurious** [coopcycle/coopcycle-web#2675] opened 2021-05-05 08:50 UTC
To be able to offer reductions (gift card). Example, a customer wants to offer 10 € to a friend, he pays and receives a code for the amount.

**Comment by alexsegura** [comment] 2021-08-05 19:41
Duplicate of #2032

**Closed by alexsegura** 2021-08-05 19:41 UTC
