### ISSUE TITLE
Negative waiting time for delivery estimate

### ISSUE THREAD

**Issue by rouelibre1** [coopcycle/coopcycle-web#1903] opened 2020-11-06 19:56 UTC
**Describe the bug**
I've seen a negative waiting time estimate while waiting for my order to be completed.
Not sure if this impacts all coopcycle instances or only occurs on kooglof (which I tried for the first time today)

**Screenshots**
![image](https://user-images.githubusercontent.com/73238613/98409121-926e6100-2072-11eb-9d86-ae5565f0fef6.png)

**Desktop :**
 - OS: Windows 10
 - Browser : Firefox 82.0.2

**Comment by alexsegura** [comment] 2020-12-23 21:23
Duplicate of #1846

**Closed by alexsegura** 2020-12-23 21:23 UTC
Labels: bug
