### ISSUE TITLE
Add "date from" and "date to" selection for .csv export under "Orders" section

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1813] opened 2020-10-09 09:25 UTC
Add the same feature of selecting multiple dates for export as it is currently with the export under `Admin dashboard`. 

Currently it allows for exporting one day only. 

![image](https://user-images.githubusercontent.com/51931067/95566310-4a2f3500-0a19-11eb-8137-d85359ead142.png)

This issue could be related to these issues: #1775, #1811, #1812 

I'm putting up all those issues because I'm thinking one issue will be easier to implement than others.

**Comment by alexsegura** [comment] 2021-01-23 11:29
Duplicate of #1972

**Closed by alexsegura** 2021-01-23 11:29 UTC
