### ISSUE TITLE
Every delivery zones are diplayed on the top left corner frame

### ISSUE THREAD

**Issue by Y00vc** [coopcycle/coopcycle-web#4590] opened 2024-08-28 15:20 UTC
As an admin, I can't see the delivery zones because they're all stacked on the top left corner.

To Reproduce
Just click on the [zones] item in the menu.

![image](https://github.com/user-attachments/assets/fa8e498a-2ec2-453d-990a-b1b7feefbbd3)

Expected behavior
I'd like to see each zone in her own frame

Device (please complete the following information):
**_- Device: PC
    OS: Linux Mint Cinnamon 5.8.4
    Firefox 121.0 64 bits_**

Additional context
This is for Lille Bike

**Comment by alexsegura** [comment] 2024-08-29 14:54
Duplicate of #4509

**Closed by alexsegura** 2024-08-29 14:54 UTC
Labels: bug
