### ISSUE TITLE
Search engine is disfunctional

### ISSUE THREAD

**Issue by AdrienSICKLO** [coopcycle/coopcycle-web#4017] opened 2024-02-20 11:43 UTC
When wanting to use the search engine, it sometimes doesn't work using the name of the client which makes it useless for a real customer. I work around it cuz I'm the one creating the forms so I can use the address, but a normal customer wouldn't

![Problem with search engine](https://github.com/coopcycle/coopcycle-web/assets/59842043/8cca4ebb-0d14-47d6-bebd-d1d0b3a3f54b)

**Comment by vladimir-8** [comment] 2024-04-03 22:30
Duplicate of https://github.com/coopcycle/coopcycle-web/issues/3821, closing this one

**Closed by vladimir-8** 2024-04-03 22:30 UTC
Labels: bug, help wanted
