### ISSUE TITLE
address field clears when making a saved address and pressing "enter" in name, phone # or business contact

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4507] opened 2024-07-11 02:09 UTC
store -> saved addresses -> create new

![Image](https://github.com/coopcycle/coopcycle-web/assets/77277854/3442745b-df97-4f44-955e-b346ed7b21d0)

**Comment by Atala** [comment] 2024-07-18 07:03
duplicate of #3509

**Closed** 2024-10-14 16:54 UTC
Labels: bug

**Comment by Atala** [comment] 2024-10-15 07:21
should be fixed actually
