### ISSUE TITLE
cant unassign a task or linked tasks by drag and drop

### ISSUE THREAD

**Issue by Paul-Eraman-CoopCycle** [coopcycle/coopcycle-web#4028] opened 2024-02-29 13:43 UTC
**Describe the bug**
when i drag a task to "unassigned" it does nothing

**To Reproduce**
drag an assigned task to no assigned
see error

**Expected behavior**
it should unassign both the task and any linked tasks

**Screenshots**
![1D9DFF08-D539-4C40-B674-E8146B9154B1_1_102_o](https://github.com/coopcycle/coopcycle-web/assets/77277854/145b2d60-152c-45ff-8307-0cc325761cb0)

**Comment by Atala** [comment] 2024-02-29 16:49
Duplicate of #3973 closing

**Closed by Atala** 2024-02-29 16:49 UTC
Labels: bug
