### ISSUE TITLE
Task gets unassigned when added to a tour assigned to the same courier

### ISSUE THREAD

**Issue by vladimir-8** [coopcycle/coopcycle-web#4549] opened 2024-08-02 18:53 UTC
**Describe the bug**

Task gets unassigned when added to a tour assigned to the same courier

**Expected behavior**

Task should stay assigned to the same courier

**Additional context**

https://coopcycle.slack.com/archives/C4UT4DGQ3/p1722437312129659

![Screenshot 2024-08-02 at 11 45 14](https://github.com/user-attachments/assets/3b9ef557-f0b6-49b2-a31a-d0dca8fe8be4)

**Comment by Atala** [comment] 2024-08-08 14:48
that is the intended behaviour, now the tour is assigned to the tasklist and the tasks are into the tour.

was there a bug linked to that?

**Closed** 2024-10-13 18:00 UTC
Labels: bug
