### ISSUE TITLE
Dragging individual or multiple tasks from a .csv upload drags the whole "folder" of tasks

### ISSUE THREAD

**Issue by agichim** [coopcycle/coopcycle-web#1961] opened 2020-12-08 00:11 UTC
**Describe the bug**
Dragging multiple tasks selected with CTRL+LCLICK from a .csv import drags the whole "folder" of tasks

**To Reproduce**
1. Go to Dashboard Map
2. Upload a .csv with multiple tasks
3. Select multiple tasks (either from the `unassigned` list or from the map, the issue is the same)
4. Drag the multiple marked (in orange) tasks, don't let go of left click.
5. The whole folder gets dragged.

**Expected behavior**
Multiple selected tasks should be dragged only, not the whole folder.

**See .gif**
![multipleTaskDragDragsWholeFolder](https://user-images.githubusercontent.com/51931067/101420246-ad3e2a80-38e9-11eb-8402-02ebe9309c48.gif)

**Comment by agichim** [comment] 2020-12-08 00:21
Draggin 1 task only doesn't work either. When you drag 1 task it drags the whole folder.

**Comment by agichim** [comment] 2020-12-08 08:09
Besides dragging individual or multiple tasks from inside a folder there should still be the option to drag the folder from the folder icon itself, if all the tasks need to be assigned to one rider

**Comment by alexsegura** [comment] 2020-12-22 14:18
You can drag individual tasks by switching to the "Display all" view.

<img width="488" alt="Capture d’écran 2020-12-22 à 15 17 38" src="https://user-images.githubusercontent.com/1162230/102897838-ef7a7680-4468-11eb-9d44-ee18787c245b.png">

**Comment by alexsegura** [comment] 2021-03-16 09:43
Duplicate of #619

**Closed by alexsegura** 2021-03-16 09:43 UTC
Labels: bug
