### ISSUE TITLE
Delivery price calculation 

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-web#3614] opened 2023-05-04 08:43 UTC
The platform should provide an easy way to calculate the price of a delivery, that can adapt to (almost) every pricing model. 
When using the platform, customers should be able to quickly see how much a delivery will cost them before booking. 
Co-ops should be able to rely on the platform for a big part of their invoicing process. 
The price calculation should support deliveries with multiple stops, and it should be possible to understand how a price was calculated. 

The price of a delivery may evolve during its lifecycle, extra costs can be added even after a delivery has been completed. 
For example, when a rider has been waiting too long at some address, we should be able to increment the price that was previously agreed with customer. 

- [x] #3047
- [ ] #3581

**Comment by r0xsh** [comment] 2023-05-04 09:44
### Additional context
As a delivery platform, we currently do not have the ability to offer multi dropoff and drop-in pricing, which can make it difficult for our customers to understand the pricing structure of our services. This lack of transparency can lead to confusion and dissatisfaction, which can ultimately harm our business. Additionally, our current pricing system is not flexible enough to accommodate the different needs of our B2B and B2C customers.

**Comment by Paul-Eraman-CoopCycle** [comment] 2024-03-30 14:16
closing during clean up because the issue is open in 3581

**Closed by Paul-Eraman-CoopCycle** 2024-03-30 14:16 UTC
Labels: EPIC
