### ISSUE TITLE
"Stores" in CoopCycle are not stores but clients (for the same-day-delivery-businesses). Please change denomination. 

### ISSUE THREAD

**Issue by 552020** [coopcycle/coopcycle-web#1518] opened 2020-06-28 11:15 UTC
Description. This is the denomination bug: the so called "store" in CoopCycle are not stores but clients for the cooperatives for normal same day delivery, where the software are used just as dispatching solution and not as a food delivery platform.  

To reproduce the bug: Try to open a store like a book store or a grocery or a wine shop. Any normal (not experienced) admin-user would click on "store" and then "open a new store". But: This way she wouldn't open a store but only a new client-account. To open a store you have to go to "restaurants", open a "new restaurant" and then in the typology you choose the kind of store you would like to open.  

Suggested solution: change the denomination "stores" in "clients". This will save a lot of misunderstandings and time for anyone learning to use the platform.

  
![Den Bug 1](https://user-images.githubusercontent.com/60273337/85945936-429fc080-b941-11ea-8336-2d76f34af268.png)

![Den Bug 2](https://user-images.githubusercontent.com/60273337/85945943-50554600-b941-11ea-8b54-9e3cf4cca89d.png)

![Den Bug 3](https://user-images.githubusercontent.com/60273337/85945947-56e3bd80-b941-11ea-9455-ad93da7a9365.png)

**Comment by alexsegura** [comment] 2020-07-03 12:43
Duplicate of #1311

**Closed by alexsegura** 2020-07-03 12:43 UTC
Labels: bug
