### ISSUE TITLE
Allow admins/restaurant owners to place an order from the backoffice

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-web#272] opened 2018-03-14 11:35 UTC

**Comment by Atala** [comment] 2023-04-25 17:21
Yes it was in this purpose. Also could be used in case of "problems"
- customer order an out-of-stock meal -> restaurant cancel the order and create a new one with new items
- some rider fucked up -> admin create a new order to have a clean state
stuff like this

**Comment by ERAMANrepartos** [comment] 2023-04-27 23:51
Is there any reason not to use "manual" deliveries for this?

In eraman we have a store for each restaurant, and if there is an issue, we make a manual order from this store, and create an incident in our incidents excel to communicate to the invoicing person about the issue and how to resolve it

Because the problem with trying to resolve the issue is that the payment is not made for the customer 

I feel like this needs a larger thought process, although our workaround is good for the moment.

**Comment by Paul-Eraman-CoopCycle** [comment] 2023-08-31 15:08
I think for the moment, for random instances it is best they call dispatch to do this, and if it is regular, a manual order works. We can make a future discussion about it though if we want. Closing

**Closed by Paul-Eraman-CoopCycle** 2023-08-31 15:08 UTC
Labels: Workaround-exists
